server:
  port: 16001
spring:
  application:
    name: "consumer-service2"
  cloud:
    loadbalancer:
      random:
        enabled: true


    resilience4j:
      instances:
        serviceA:
          circuitBreaker:
            enabled: true
            failureRateThreshold: 30
            slidingWindowType: TIME_BASED
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 5000ms
            permittedNumberOfCallsInHalfOpenState: 3


          serviceB:
            circuitBreaker:
              enabled: true
              failureRateThreshold: 50
              slowCallRateThreshold: 30
              slowCallDurationThreshold: 2s
              slidingWindowType: TIME_BASED
              slidingWindowSize: 10
              minimumNumberOfCalls: 5
              waitDurationInOpenState: 5000ms
              permittedNumberOfCallsInHalfOpenState: 3

          serviceC:
            bulkhead:
              enabled: true
              maxConcurrentCalls: 10
              maxWaitDuration: 20ms

          serviceD:
            rateLimiter:
              enabled: true
              limitForPeriod: 5
              limitRefreshPeriod: 2s

eureka:
  instance:
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/"



#resilience4j:
#  retry:
#    configs:
#      default:
#        max-attempts: 3 #最大重试次数
#        wait-duration: 1000 #重试间隔时间
#        retry-exceptions:
#          - java.lang.Exception #出现该异常就重试
#    instances:
#      retry1:
#        base-config: default
#      retry2:
#        base-config: default
#        max-attempts: 5
#        wait-duration: 500



#  circuitbreaker:
#    configs:
#      default:
#        waitDurationInOpenState: 5000 # 熔断器从打开到半开需要的时间
#        failure-rate-threshold: 10  # 熔断器打开的失败阈值
#        event-consumer-buffer-size: 5 #事件缓冲区大小
#        automatic-transition-from-open-to-half-open-enabled: true # 是否自动从打开到半开
#        recordExceptions: java.lang.Exception  # 记录的异常
#        register-health-indicator: false # 健康监测
#        minimum-number-of-calls: 1 #触发熔断机制的最⼩请求个数
#        permitted-number-of-calls-in-half-open-state: 2 #HALF_OPEN状态的时候，允许通过的请求个数
#    instances:
#      backendA:
#        base-config: default
#      backendB:
#        base-config: default
#        wait-duration-in-open-state: 3000
#        failure-rate-threshold: 15

#resilience4j:
#  ratelimiter:
#    configs:
#      default:
#        limit-for-period: 10
#        limit-refresh-period:
#          seconds: 1
#        timeout-duration:
#          seconds: 1
#
#    instances:
#      rate1:
#        base-config: default
#
#      rate2:
#        base-config: default
#        timeout-duration:
#          seconds: 2

#
#resilience4j:
#  bulkhead:
#    configs:
#      default:
#        max-concurrent-calls: 5
#        max-wait-duration:
#          seconds: 0
#
#    instances:
#      bulkheadA:
#        base-config: default
#
#      bulkheadB:
#        base-config: default
#        max-wait-duration:
#          seconds: 2
#
#resilience4j:
#  timelimiter:
#    configs:
#      default:
#        timeout-duration:
#          seconds: 1
#        cancel-running-future: true
#    instances:
#      timelimiterA:
#        base-config: default